/**
 * WHAT BRIEFCASE NEEDS FROM A SERVER, and the two mechanical halves of
 * stating it: posting the module, and following the task it starts.
 *
 * Ported from BookForge's electron/crucible/module-setup.ts. The module file
 * (`module/briefcase.module.json`) is GENERATED by the crucible repo's
 * `scripts/gen-modules.py` from `modules/briefcase.toml` and vendored byte for
 * byte; `module/briefcase.toml` beside it is the declaration, and says how the
 * JSON is regenerated. `test/crucible/module-file.spec.ts` keeps the copy honest.
 *
 * WHEN this is posted is `coordinate.service.ts`'s decision (only when a read
 * says something is missing). This file only posts and follows.
 */
import type { CrucibleClient, CrucibleModule, SubjectKind } from '@crucible/client';
import { CrucibleFieldMissing } from './errors';
import type { CrucibleModuleProgress, CrucibleUnmetClass } from './wire/coordinate-wire';

// `import = require`: the backend compiles to CommonJS without esModuleInterop,
// where a default import of JSON is undefined.
import briefcaseModule = require('./module/briefcase.module.json');

/** What Briefcase asks a Crucible for: the generated file, unedited. */
export const BRIEFCASE_MODULE: CrucibleModule = briefcaseModule as CrucibleModule;

interface Scoped {
  backends?: readonly string[];
}

/**
 * The module THIS backend can serve, with the generated `backends` key stripped.
 *
 * The server's `validate_module` refuses any key on a job type other than
 * `type` and `narrator_engine`, and any on a subject other than `kind` and `id`
 * (INTEGRATING-AN-APP.md §3.1). So each entry is filtered to the server's
 * `info().host.backend` and rebuilt from its wire fields. An entry with no
 * `backends` means "everywhere", as it did before the field existed.
 */
export function moduleForBackend(backend: string, module: CrucibleModule = BRIEFCASE_MODULE): CrucibleModule {
  const here = (entry: Scoped): boolean => entry.backends === undefined || entry.backends.includes(backend);
  const job_types = module.job_types
    .filter((entry) => here(entry as Scoped))
    .map(({ type, narrator_engine }) => (narrator_engine === undefined ? { type } : { type, narrator_engine }));
  const subjects = module.subjects
    .filter((subject) => here(subject as Scoped))
    .map((subject) => ({ kind: subject.kind as SubjectKind, id: subject.id }));
  const needs = module.needs.map((need) => ({ class: need.class }));
  return { name: module.name, version: module.version, job_types, needs, subjects };
}

/**
 * Post the module to the engine behind `client`. Answers the task id and throws
 * every refusal untranslated: `coordinate.service.ts` tells `server_busy` (a
 * wait), `task_busy` (follow the other one) and a refusal about the request
 * (once, by name) apart, and each is a different act.
 *
 * The backend is ASKED of the server immediately before posting, not cached:
 * which transcriber a machine can hold is its own fact.
 */
export async function postBriefcaseModule(client: CrucibleClient, server: string | null = null): Promise<string> {
  const backend = (await client.info()).host.backend;
  // Load-bearing here (the SDK reads it as informational): the module's
  // entries are filtered to it, and no backend is a safe guess.
  if (backend === null) throw new CrucibleFieldMissing(server, 'host.backend (GET /v1/info)', 'choose the parts of its module this machine can run');
  return client.submitTask({ type: 'module', module: moduleForBackend(backend) });
}

/**
 * Follow a task to its end, one progress value per event. Resolves with the
 * state it reached and never throws on `failed`: a failed module is something
 * a screen draws, not an exception. The task may be ours or somebody else's
 * (a Crucible runs one task at a time, and joining the running one beats
 * queueing a second).
 *
 * After the stream, `GET /v1/tasks/{id}` is read once for `unmet`, which lives
 * on the task document and on no frame. A read that fails leaves `unmet` null
 * ("nobody said"), and does not fail a task that ran to `done`.
 */
export async function followCrucibleTask(
  client: CrucibleClient,
  server: string,
  taskId: string,
  onProgress: (progress: CrucibleModuleProgress) => void,
): Promise<CrucibleModuleProgress> {
  let last: CrucibleModuleProgress = {
    server, taskId, state: 'running', step: null, line: null, bytes: null, skipped: null, jobTypes: null, error: null, unmet: null,
  };
  onProgress(last);

  for await (const event of client.taskEvents(taskId)) {
    switch (event.event) {
      case 'started':
        last = { ...last, state: 'running' };
        break;
      case 'step':
        last = {
          ...last,
          state: 'running',
          step: { name: event.data.name, index: event.data.index, total: event.data.total },
          jobTypes: event.data.jobTypes === undefined ? last.jobTypes : [...event.data.jobTypes],
          line: null,
          bytes: null,
          skipped: null,
        };
        break;
      case 'progress':
        last = 'line' in event.data
          ? { ...last, line: event.data.line, bytes: null }
          : { ...last, line: null, bytes: { done: event.data.bytesDone, total: event.data.bytesTotal, file: event.data.file } };
        break;
      case 'skipped':
        last = { ...last, skipped: event.data.reason };
        break;
      case 'done':
        last = { ...last, state: 'done', line: null, bytes: null, error: null };
        break;
      case 'failed':
        // The steps that completed stay on disk; pressing again skips them.
        last = { ...last, state: 'failed', error: { code: event.data.code, message: event.data.message } };
        break;
      case 'cancelled':
        last = { ...last, state: 'cancelled' };
        break;
      default:
        // An event kind this build has never heard of: ignore the frame, keep the stream.
        break;
    }
    onProgress(last);
  }

  try {
    const status = await client.task(taskId);
    const unmet: CrucibleUnmetClass[] = status.unmet.map((need) => ({ class: need.class, reason: need.reason }));
    last = { ...last, unmet };
    onProgress(last);
  } catch {
    // `unmet` stays null: the stream already said what happened to the work.
  }
  return last;
}
